# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='readinglistentry',
            order_with_respect_to='resource_list',
        ),
        migrations.AlterOrderWithRespectTo(
            name='vocabularylistentry',
            order_with_respect_to='resource_list',
        ),
    ]
