# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortdef', models.TextField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_vocabulary.Lemma'),
        ),
    ]
