# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageLemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='deep_vocabulary.Lemma')),
            ],
        ),
        migrations.CreateModel(
            name='TextEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cts_urn', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='definition',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='deep_vocabulary.Lemma'),
        ),
        migrations.AddField(
            model_name='passagelemma',
            name='text_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_lemmas', to='deep_vocabulary.TextEdition'),
        ),
    ]
