# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0002_auto_20171207_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='textedition',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
