# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0003_textedition_is_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='core_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='corpus_count',
            field=models.IntegerField(null=True),
        ),
    ]
