# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0004_auto_20171209_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='core_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='corpus_count',
            field=models.IntegerField(default=0),
        ),
    ]
