# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0005_auto_20171210_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='textedition',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
