# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0006_textedition_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='unaccented',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
