# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0007_lemma_unaccented'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lemma',
            index=models.Index(fields=['unaccented'], name='deep_vocabu_unaccen_9ad329_idx'),
        ),
    ]
