# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 23:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0008_auto_20171213_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagelemma',
            name='ref1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None),
        ),
        migrations.AddField(
            model_name='passagelemma',
            name='ref2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None),
        ),
        migrations.AddField(
            model_name='passagelemma',
            name='ref3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None),
        ),
        migrations.AddField(
            model_name='passagelemma',
            name='ref4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None),
        ),
    ]
