# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_vocabulary', '0009_auto_20171213_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='sort_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='lemma',
            index=models.Index(fields=['sort_key'], name='deep_vocabu_sort_ke_6920c9_idx'),
        ),
    ]
